server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/E-commerce}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:elan7771}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
