import type { Product, Category, Order, Review, RevenueData } from "@/types";

// ─── Categories ───────────────────────────────────────────────────────
export const mockCategories: Category[] = [
  { id: "1", name: "Electronics", slug: "electronics", icon: "💻", image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&q=80", color: "#6366f1", productCount: 15420 },
  { id: "2", name: "Fashion", slug: "fashion", icon: "👗", image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&q=80", color: "#ec4899", productCount: 28340 },
  { id: "3", name: "Home & Living", slug: "home-living", icon: "🏠", image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80", color: "#10b981", productCount: 12580 },
  { id: "4", name: "Sports", slug: "sports", icon: "⚽", image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400&q=80", color: "#f59e0b", productCount: 8920 },
  { id: "5", name: "Books", slug: "books", icon: "📚", image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&q=80", color: "#8b5cf6", productCount: 45000 },
  { id: "6", name: "Beauty", slug: "beauty", icon: "💄", image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&q=80", color: "#f43f5e", productCount: 9340 },
  { id: "7", name: "Gaming", slug: "gaming", icon: "🎮", image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&q=80", color: "#06b6d4", productCount: 6780 },
  { id: "8", name: "Automotive", slug: "automotive", icon: "🚗", image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&q=80", color: "#64748b", productCount: 4210 },
];

// ─── Mock Seller ──────────────────────────────────────────────────────
const mockSeller = {
  id: "s1",
  name: "TechZone Official",
  logo: "https://api.dicebear.com/7.x/shapes/svg?seed=TechZone",
  rating: 4.8,
  verified: true,
  totalSales: 128000,
  joinedAt: "2021-03-15",
};

// ─── Products ─────────────────────────────────────────────────────────
export const mockProducts: Product[] = [
  {
    id: "p1",
    slug: "apple-macbook-pro-m3",
    name: "Apple MacBook Pro 14\" M3 Pro",
    description: "The most powerful MacBook Pro ever is here. With Apple M3 Pro chip, this laptop delivers unprecedented performance for professionals.",
    shortDescription: "Apple M3 Pro chip · 18GB RAM · 512GB SSD · 14-inch Liquid Retina XDR",
    price: 189900,
    originalPrice: 219900,
    discount: 14,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=90",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=600&q=90",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&q=90",
    ],
    category: mockCategories[0],
    brand: "Apple",
    seller: mockSeller,
    rating: 4.9,
    reviewCount: 2847,
    stock: 45,
    sku: "APL-MBP14-M3-512",
    tags: ["laptop", "macbook", "apple", "m3", "pro"],
    specifications: {
      "Processor": "Apple M3 Pro (12-core CPU)",
      "RAM": "18GB Unified Memory",
      "Storage": "512GB SSD",
      "Display": "14.2-inch Liquid Retina XDR",
      "Battery": "Up to 18 hours",
      "Weight": "1.61 kg",
      "Ports": "3x Thunderbolt 4, HDMI, SD Card, MagSafe 3",
    },
    isFeatured: true,
    isFlashSale: false,
    isBestSeller: true,
    isNew: false,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-06-20T14:30:00Z",
    estimatedDelivery: "2-3 business days",
    returnPolicy: "30-day return policy",
    warranty: "1 year limited warranty",
  },
  {
    id: "p2",
    slug: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra 256GB",
    description: "The ultimate smartphone experience with Galaxy AI. Titanium design, S Pen included, and the brightest display ever on a Galaxy phone.",
    shortDescription: "Galaxy AI · Snapdragon 8 Gen 3 · 200MP Camera · S Pen · 12GB RAM",
    price: 129999,
    originalPrice: 134999,
    discount: 4,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=90",
      "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=90",
    ],
    category: mockCategories[0],
    brand: "Samsung",
    seller: mockSeller,
    rating: 4.7,
    reviewCount: 8923,
    stock: 120,
    sku: "SAM-S24U-256",
    tags: ["smartphone", "samsung", "galaxy", "android", "5g"],
    specifications: {
      "Processor": "Snapdragon 8 Gen 3",
      "RAM": "12GB",
      "Storage": "256GB",
      "Display": "6.8-inch QHD+ Dynamic AMOLED",
      "Camera": "200MP + 50MP + 12MP + 10MP",
      "Battery": "5000mAh",
    },
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    isBestSeller: true,
    isNew: true,
    createdAt: "2024-02-17T08:00:00Z",
    updatedAt: "2024-06-18T11:00:00Z",
    estimatedDelivery: "1-2 business days",
    returnPolicy: "10-day return policy",
    warranty: "1 year manufacturer warranty",
  },
  {
    id: "p3",
    slug: "sony-wh1000xm5-headphones",
    name: "Sony WH-1000XM5 Wireless Headphones",
    description: "Industry-leading noise canceling with the next generation processor and dual noise sensor technology.",
    shortDescription: "30-hr battery · Industry-leading ANC · Hi-Res Audio · LDAC",
    price: 24990,
    originalPrice: 34990,
    discount: 29,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=90",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=90",
    ],
    category: mockCategories[0],
    brand: "Sony",
    seller: mockSeller,
    rating: 4.8,
    reviewCount: 15234,
    stock: 230,
    sku: "SNY-WH1000XM5-BLK",
    tags: ["headphones", "wireless", "noise-canceling", "sony", "audio"],
    specifications: {
      "Driver": "30mm",
      "Battery": "30 hours ANC on",
      "Charging": "USB-C, 3-min quick charge = 3hrs",
      "Connectivity": "Bluetooth 5.2, NFC",
      "Weight": "250g",
    },
    isFeatured: true,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    isBestSeller: false,
    isNew: false,
    createdAt: "2023-11-10T09:00:00Z",
    updatedAt: "2024-06-15T16:00:00Z",
    estimatedDelivery: "2-4 business days",
    returnPolicy: "30-day return policy",
    warranty: "1 year limited warranty",
  },
  {
    id: "p4",
    slug: "nike-air-max-270",
    name: "Nike Air Max 270 Running Shoes",
    description: "Designed for all-day wear, the Nike Air Max 270 delivers exceptional cushioning and style.",
    shortDescription: "Max Air heel unit · Mesh upper · Foam midsole · Available in 8 colors",
    price: 11995,
    originalPrice: 14995,
    discount: 20,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=90",
      "https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?w=600&q=90",
    ],
    category: mockCategories[3],
    brand: "Nike",
    seller: { ...mockSeller, id: "s2", name: "SportsMart" },
    rating: 4.5,
    reviewCount: 6234,
    stock: 85,
    sku: "NK-AM270-BLK-10",
    tags: ["shoes", "nike", "running", "sports", "airmax"],
    specifications: {
      "Upper": "Mesh with synthetic overlays",
      "Midsole": "Foam + Max Air heel unit",
      "Outsole": "Rubber",
      "Fit": "True to size",
    },
    isFeatured: false,
    isFlashSale: false,
    isBestSeller: true,
    isNew: false,
    createdAt: "2023-09-05T07:00:00Z",
    updatedAt: "2024-06-01T12:00:00Z",
    estimatedDelivery: "3-5 business days",
    returnPolicy: "30-day return policy",
  },
  {
    id: "p5",
    slug: "ipad-pro-m4-13inch",
    name: "Apple iPad Pro 13\" M4 Wi-Fi 256GB",
    description: "Impossibly thin. Incredibly powerful. iPad Pro with the M4 chip and stunning Ultra Retina XDR display.",
    shortDescription: "Apple M4 · Ultra Retina XDR · OLED · Apple Pencil Pro compatible",
    price: 119900,
    originalPrice: 119900,
    discount: 0,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=90",
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&q=90",
    ],
    category: mockCategories[0],
    brand: "Apple",
    seller: mockSeller,
    rating: 4.8,
    reviewCount: 1823,
    stock: 30,
    sku: "APL-IPAD-PRO13-M4-256",
    tags: ["ipad", "apple", "tablet", "m4", "pro"],
    specifications: {
      "Chip": "Apple M4",
      "Display": "13-inch Ultra Retina XDR OLED",
      "Storage": "256GB",
      "Camera": "12MP Wide, LiDAR Scanner",
      "Battery": "Up to 10 hours",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
    },
    isFeatured: true,
    isFlashSale: false,
    isBestSeller: false,
    isNew: true,
    createdAt: "2024-05-07T10:00:00Z",
    updatedAt: "2024-06-20T09:00:00Z",
    estimatedDelivery: "1-3 business days",
    returnPolicy: "14-day return policy",
    warranty: "1 year limited warranty",
  },
  {
    id: "p6",
    slug: "dyson-v15-detect-vacuum",
    name: "Dyson V15 Detect Absolute Vacuum",
    description: "The most powerful, intelligent vacuum cleaner Dyson has ever made. Laser reveals invisible dust.",
    shortDescription: "HEPA filtration · 60-min runtime · Laser dust detection · 5-stage filtration",
    price: 52900,
    originalPrice: 62900,
    discount: 16,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=90",
    ],
    category: mockCategories[2],
    brand: "Dyson",
    seller: { ...mockSeller, id: "s3", name: "HomeEssentials" },
    rating: 4.6,
    reviewCount: 3421,
    stock: 18,
    sku: "DYS-V15-DETECT-ABS",
    tags: ["vacuum", "dyson", "cordless", "home", "cleaning"],
    specifications: {
      "Suction": "230 AW",
      "Runtime": "Up to 60 min",
      "Weight": "3.1 kg",
      "Filter": "HEPA filtration",
    },
    isFeatured: false,
    isFlashSale: true,
    flashSaleEndsAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    isBestSeller: false,
    isNew: false,
    createdAt: "2023-08-20T11:00:00Z",
    updatedAt: "2024-05-30T08:00:00Z",
    estimatedDelivery: "3-5 business days",
    returnPolicy: "30-day return policy",
    warranty: "2 year warranty",
  },
  {
    id: "p7",
    slug: "lg-oled-c3-65-tv",
    name: "LG C3 65\" OLED evo 4K Smart TV",
    description: "Experience self-lit pixels for perfect blacks, filmmaker mode, and next-gen gaming features.",
    shortDescription: "α9 AI Processor 4K Gen6 · Dolby Vision/Atmos · 4 HDMI 2.1 · 120Hz",
    price: 139990,
    originalPrice: 189990,
    discount: 26,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=600&q=90",
    ],
    category: mockCategories[0],
    brand: "LG",
    seller: mockSeller,
    rating: 4.9,
    reviewCount: 4123,
    stock: 12,
    sku: "LG-OLED65C3-2023",
    tags: ["tv", "oled", "lg", "4k", "smart-tv", "gaming"],
    specifications: {
      "Display": "65\" OLED evo",
      "Resolution": "4K Ultra HD (3840x2160)",
      "HDR": "Dolby Vision, HDR10, HLG",
      "Refresh Rate": "120Hz",
      "HDMI": "4x HDMI 2.1",
      "Audio": "60W, Dolby Atmos",
    },
    isFeatured: true,
    isFlashSale: false,
    isBestSeller: true,
    isNew: false,
    createdAt: "2023-06-10T08:00:00Z",
    updatedAt: "2024-06-10T15:00:00Z",
    estimatedDelivery: "5-7 business days",
    returnPolicy: "10-day return policy",
    warranty: "1 year comprehensive",
  },
  {
    id: "p8",
    slug: "kindle-paperwhite-2024",
    name: "Kindle Paperwhite 2024 - 16GB",
    description: "The thinnest, lightest Kindle Paperwhite ever, with a 7\" glare-free display and weeks of battery.",
    shortDescription: "7\" glare-free display · 16GB · Waterproof · 12 weeks battery · USB-C",
    price: 15999,
    originalPrice: 17999,
    discount: 11,
    currency: "INR",
    images: [
      "https://images.unsplash.com/photo-1592424002053-21f369ad7fdb?w=600&q=90",
    ],
    category: mockCategories[4],
    brand: "Amazon",
    seller: { ...mockSeller, id: "s4", name: "BookWorld" },
    rating: 4.7,
    reviewCount: 28901,
    stock: 500,
    sku: "AMZ-KPW-16GB-2024",
    tags: ["kindle", "ereader", "amazon", "books", "reading"],
    specifications: {
      "Display": "7\" 300 ppi Paperwhite",
      "Storage": "16GB",
      "Battery": "Up to 12 weeks",
      "Waterproof": "IPX8 (2m for 60 min)",
      "Connectivity": "Wi-Fi 5, Bluetooth",
    },
    isFeatured: false,
    isFlashSale: false,
    isBestSeller: true,
    isNew: true,
    createdAt: "2024-04-01T09:00:00Z",
    updatedAt: "2024-06-18T13:00:00Z",
    estimatedDelivery: "1-2 business days",
    returnPolicy: "30-day return policy",
    warranty: "1 year limited warranty",
  },
];

// ─── Mock Reviews ─────────────────────────────────────────────────────
export const mockReviews: Review[] = [
  {
    id: "r1",
    userId: "u1",
    productId: "p1",
    user: { name: "Rahul Sharma", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul" },
    rating: 5,
    title: "Absolutely incredible machine!",
    body: "I've been using the MacBook Pro M3 Pro for three months now and it completely changed my workflow. The performance is unmatched — I can run Final Cut Pro, Xcode, and multiple apps simultaneously without any slowdown.",
    isVerifiedPurchase: true,
    helpfulCount: 234,
    createdAt: "2024-04-20T10:30:00Z",
  },
  {
    id: "r2",
    userId: "u2",
    productId: "p1",
    user: { name: "Priya Menon", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya" },
    rating: 5,
    title: "Worth every rupee",
    body: "As a software engineer, this laptop is a beast. Compiles code faster than any machine I've used. Battery life is genuinely impressive — easily get 12 hours of actual coding work.",
    isVerifiedPurchase: true,
    helpfulCount: 187,
    createdAt: "2024-05-12T14:00:00Z",
  },
];

// ─── Revenue Data ─────────────────────────────────────────────────────
export const mockRevenueData: RevenueData[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    date: date.toISOString().split("T")[0],
    revenue: Math.floor(Math.random() * 500000 + 200000),
    orders: Math.floor(Math.random() * 500 + 200),
    visitors: Math.floor(Math.random() * 5000 + 2000),
  };
});

// ─── Flash Sale Products ──────────────────────────────────────────────
export const flashSaleProducts = mockProducts.filter((p) => p.isFlashSale);

// ─── Best Sellers ─────────────────────────────────────────────────────
export const bestSellers = mockProducts.filter((p) => p.isBestSeller);

// ─── Trending Products ─────────────────────────────────────────────────
export const trendingProducts = [...mockProducts].sort(() => Math.random() - 0.5).slice(0, 6);

// ─── Popular Searches ─────────────────────────────────────────────────
export const popularSearches = [
  "MacBook Pro", "iPhone 15", "Gaming Laptop", "Wireless Headphones",
  "Smart Watch", "Air Purifier", "Running Shoes", "4K TV",
];
